# the name used to display in the OS. Specifically desktop entry name
display_name: Slides

# package name for debian/apt repository
# the name should be all lowercase with -+.
package_name: slides

maintainer:
  name: Koorb Notsyor
  email: koorb.notsyor@gmail.com
  
#co_authors:
#  name:
#  email: 

# enum options -> required, important, standard, optional, extra
# refer: https://www.debian.org/doc/debian-policy/ch-archive.html#s-priorities
priority: optional

# enum options: admin, cli-mono, comm, database, debug, devel, doc, editors, education, electronics, embedded, fonts, games, gnome, gnu-r, gnustep, graphics, hamradio, haskell, httpd, interpreters, introspection, java, javascript, kde, kernel, libdevel, libs, lisp, localization, mail, math, metapackages, misc, net, news, ocaml, oldlibs, otherosfs, perl, php, python, ruby, rust, science, shells, sound, tasks, tex, text, utils, vcs, video, web, x11, xfce, zope
# refer: https://www.debian.org/doc/debian-policy/ch-archive.html#s-subsections
section: graphics

# the size of binary in kilobyte
installed_size: 24

# direct dependencies required by the application
# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
#        => 404 ????
# ?refer: https://www.debian.org/doc/debian-policy/ch-archive.html#
dependencies:
#  - mpv

essential: false

# application icon path relative to project url
icon: linux/assets/slideshow.png


postinstall_scripts:
  - echo "Hello..."
postuninstall_scripts:
  - echo "Good-bye..."

keywords:
  - Slideshow
  - Flutter 

# a name to categorize the app into a section of application
generic_name: Slide show

# the categories the application belong to
# refer: https://specifications.freedesktop.org/menu-spec/latest/
categories:
  - Graphics
  - Utility

# let OS know if the application can be run on start_up. If it's false
# the application will deny to the OS if it was added as a start_up
# application
startup_notify: true
